#!/bin/sh

docker -v
if [[ $? != 0 ]]
then
    echo 'Install Docker before!'
    echo 'Or use `git commit --no-verify`'
fi

PHP="docker run --rm --name php-cli -v "/$(PWD)"://www -w="//www" php:7.1-alpine"
PROJECT=`docker run --rm --name php-cli -v "/$(PWD)"://www -w="//www" php:7.1-alpine -r 'echo dirname(dirname(dirname(realpath("'$0'"))));'`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [[ "$#" -eq 1 ]]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=${oIFS}
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in ${SFILES}
do
    ${PHP} -l -d display_errors=0 /${PROJECT}/${FILE}
    if [[ $? != 0 ]]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES /$PROJECT/$FILE"
done

if [[ "$FILES" != "" ]]
then
    ${PHP} ./vendor/bin/phpcs --standard=PSR2 --colors --encoding=utf-8 -n -p ${FILES}
    if [[ $? != 0 ]]
    then
        echo "Fix the error before commit!"
        echo "Run"
        echo "  ./vendor/bin/phpcbf --standard=PSR2 $FILES"
        echo "for automatic fix or fix it manually."
        exit 1
    fi
fi
exit $?